msg:
	@echo "Options:\n\tdice - play dice game.\n\tlogger - run logger."

dice:
	clang++ templateMethodGames.cpp -o dice.out

logger:
	clang++ logger_main.cpp -o log.out

clean:
	rm -rf log.out
	rm -rf dice.out
	